### ISSUE TITLE
URL para o repositório provisória e permanente

### ISSUE THREAD

**Issue by rcgivisiez** [webiwg/acessibilidade-web-pt#10]
Tanto para o projeto de textos de acessibilidade quanto para o de história, é pertinente ter nesse momento 1) URL provisória e 2) URL permanente.

Em ambos os casos, é importante deixar a URL no topo da tela do Github.

Depende em parte do issue #1.

**Comment by fititnt** [comment]
Ops. Estava resolvido e esquecemos de fechar isto
